// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaylocityCodingExercise.Model.DBContexts;

#nullable disable

namespace PaylocityCodingExercise.Model.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230713004740_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("PaylocityCodingExercise.Model.Models.Dependent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dependents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            Name = "Obi-Wan Kenobi"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 1,
                            Name = "Barbara Connors"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 2,
                            Name = "Dave Mathews"
                        });
                });

            modelBuilder.Entity("PaylocityCodingExercise.Model.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BenefitsPackage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SalaryRaw")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BenefitsPackage = "Type A",
                            Name = "Andrew Miller",
                            SalaryRaw = 52000
                        },
                        new
                        {
                            Id = 2,
                            BenefitsPackage = "Type B",
                            Name = "Bobby Flay",
                            SalaryRaw = 52000
                        },
                        new
                        {
                            Id = 3,
                            BenefitsPackage = "Type C",
                            Name = "Luke Skywalker",
                            SalaryRaw = 52000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
