const API_BASE_URL = `https://localhost:7076`;

const ENDPOINTS = {
    GET_ALL_EMPLOYEES: `get-all-employees`,
    GET_EMPLOYEE_BY_ID: `get-employee-by-id`,
    CREATE_EMPLOYEE: `create-employee`,
    UPDATE_EMPLOYEE: `update-employee`,
    DELETE_EMPLOYEE_BY_ID: `delete-employee-by-id`,
    GET_ALL_DEPENDENTS: `get-all-dependents`,
    GET_DEPENDENTS_BY_EMPLOYEE_ID: `get-dependents-by-employee-id`,
    GET_DEPENDENTS_BY_ID: `get-dependents-by-id`,
    CREATE_DEPENDENT: `create-dependent`,
    UPDATE_DEPENDENT: `update-dependent`,
    DELETE_DEPENDENT_BY_ID: `delete-dependent-by-id`
};

const development = {
    API_URL_GET_ALL_EMPLOYEES: `${API_BASE_URL}/${ENDPOINTS.GET_ALL_EMPLOYEES}`,
    API_URL_GET_EMPLOYEE_BY_ID: `${API_BASE_URL}/${ENDPOINTS.GET_EMPLOYEE_BY_ID}`,
    API_URL_CREATE_EMPLOYEE: `${API_BASE_URL}/${ENDPOINTS.CREATE_EMPLOYEE}`,
    API_URL_UPDATE_EMPLOYEE: `${API_BASE_URL}/${ENDPOINTS.UPDATE_EMPLOYEE}`,
    API_URL_DELETE_EMPLOYEE_BY_ID: `${API_BASE_URL}/${ENDPOINTS.DELETE_EMPLOYEE_BY_ID}`,
    API_URL_GET_ALL_DEPENDENTS: `${API_BASE_URL}/${ENDPOINTS.GET_ALL_DEPENDENTS}`,
    API_URL_GET_DEPENDENTS_BY_EMPLOYEE_ID: `${API_BASE_URL}/${ENDPOINTS.GET_DEPENDENTS_BY_EMPLOYEE_ID}`,
    API_URL_GET_DEPENDENTS_BY_ID: `${API_BASE_URL}/${ENDPOINTS.GET_DEPENDENTS_BY_ID}`,
    API_URL_CREATE_DEPENDENT: `${API_BASE_URL}/${ENDPOINTS.CREATE_DEPENDENT}`,
    API_URL_UPDATE_DEPENDENT: `${API_BASE_URL}/${ENDPOINTS.UPDATE_DEPENDENT}`,
    API_URL_DELETE_DEPENDENT_BY_ID: `${API_BASE_URL}/${ENDPOINTS.DELETE_DEPENDENT_BY_ID}`,

}

const Constants = development;

export default Constants;